{% set name = "napari-itk-io" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/napari-itk-io-{{ version }}.tar.gz
  sha256: 95b34bdfddde4b2afe5162319445fdbcc551a59ba266c93096aaf85e9210a93e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools-scm
  run:
    - itk >=5.2.0
    - itk-napari-conversion
    - napari-plugin-engine >=0.2.0
    - numpy
    - python >=3.8

test:
  imports:
    - napari_itk_io
  commands:
    - pip list
    # - pip check
  requires:
    - pip

about:
  home: https://github.com/InsightSoftwareConsortium/napari-itk-io
  summary: File IO with itk for napari
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
    - thewtex
