{% set name = "napari-itk-io" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/napari-itk-io-{{ version }}.tar.gz
  sha256: 99c9c740614585bd5051437d0516b62d72148940f814d4740c79db870ce87c82

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools-scm
  run:
    - itk >=5.2.0
    - itk-napari-conversion
    - napari-plugin-engine >=0.2.0
    - numpy
    - python >=3.6

test:
  imports:
    - napari_itk_io
  commands:
    - pip list
    # - pip check
  requires:
    - pip

about:
  home: https://github.com/InsightSoftwareConsortium/napari-itk-io
  summary: File IO with itk for napari
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - conda-forge/napari
    - thewtex
