{% set name = "napari-itk-io" %}
{% set version = "0.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 13258f77a9f646f416cdda97b2bcfc7b49eb6c1aee42de54b6ff7b9cee0eb0da

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools-scm
  run:
    - itk >=5.2.0
    - itk-napari-conversion
    - napari
    - napari-plugin-engine >=0.2.0
    - numpy
    - python >=3.8

test:
  imports:
    - napari_itk_io
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/InsightSoftwareConsortium/napari-itk-io
  summary: File IO with itk for napari
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
    - thewtex
